Repository jenkinsci/swarm-plugin, pull requests merged in 2021-04, with the labels that each got.

#316 Adapt to jenkinsci/jenkins-test-harness#261; test against latest LTS
  Jenkinsfile
  plugin/src/test/java/hudson/plugins/swarm/test/GlobalSecurityConfigurationBuilder.java
Labels: test

#318 README.adoc: add common rationales for Swarm in the intro
  README.adoc
Labels: documentation

#322 Use consistent terminology for Jenkins controller
  README.adoc
  client/src/main/java/hudson/plugins/swarm/Client.java
  client/src/main/java/hudson/plugins/swarm/LabelFileWatcher.java
  client/src/main/java/hudson/plugins/swarm/Options.java
  client/src/main/java/hudson/plugins/swarm/SwarmClient.java
  client/src/test/java/hudson/plugins/swarm/ClientTest.java
  plugin/src/main/java/hudson/plugins/swarm/PluginImpl.java
  plugin/src/test/java/hudson/plugins/swarm/PipelineJobTest.java
  plugin/src/test/java/hudson/plugins/swarm/SwarmClientIntegrationTest.java
  plugin/src/test/java/hudson/plugins/swarm/test/GlobalSecurityConfigurationBuilder.java
  plugin/src/test/java/hudson/plugins/swarm/test/SwarmClientRule.java
Labels: feature
