Repository jenkinsci/swarm-plugin, pull requests merged in 2022-10, with the labels that each got.

#488 Remove dependency on OSHI
  client/pom.xml
  client/src/main/java/hudson/plugins/swarm/Client.java
  plugin/pom.xml
  plugin/src/test/java/hudson/plugins/swarm/SwarmClientIntegrationTest.java
Labels: internal

#481 Prefer Java 11 links to Java 8 links
  client/src/main/java/hudson/plugins/swarm/Client.java
  docs/logging.adoc
  docs/proxy.adoc
Labels: skip-changelog

#489 Remove dependency on `commons-codec`
  client/pom.xml
  client/src/main/java/hudson/plugins/swarm/SwarmClient.java
Labels: internal

#490 Adopt POM Code Convention
  client/pom.xml
  plugin/pom.xml
  pom.xml
Labels: internal

#487 Check path of old PID (if running) before exiting
  client/src/main/java/hudson/plugins/swarm/Client.java
  plugin/src/test/java/hudson/plugins/swarm/SwarmClientIntegrationTest.java
Labels: bug

#493 Migrate from Apache HttpComponents Client to Java Platform HTTP client
  client/pom.xml
  client/src/main/java/hudson/plugins/swarm/Client.java
  client/src/main/java/hudson/plugins/swarm/LabelFileWatcher.java
  client/src/main/java/hudson/plugins/swarm/SwarmClient.java
  client/src/test/java/hudson/plugins/swarm/SwarmClientTest.java
  docs/proxy.adoc
Labels: dependencies, feature, java
